Diagnostics:
    UnusedIncludes: Strict
    MissingIncludes: Relaxed

InlayHints:
    BlockEnd: No
    Designators: Yes
    Enabled: No
    ParameterNames: Yes
    DeducedTypes: Yes
    TypeNameLimit: 24

Hover:
    ShowAKA: No

If:
    PathMatch: [ .*\.c ]
CompileFlags:
    Add: [
        -Wall,
        -Wextra,
        -Wpedantic,
        -Wconversion,
        -Wshadow,
        -Wnull-dereference,
        -Weverything,
        -Wno-declaration-after-statement,   #"Mixing declarations and code is incompatible with standards before c99."
        -Wno-cast-align,                    # Misalignment occurs when casting from u16* to u32* or similar.
        -Wno-documentation,
        -Wno-documentation-unknown-command,
        -Wno-unsafe-buffer-usage,
        -Wno-covered-switch-default,
        -Wno-switch,
        # -std=c99,
        -fparse-all-comments,
        -ferror-limit=0,
    ]
If:
    PathMatch: [ .*\.cpp ]
CompileFlags:
    Add: [
        -Wall,
        -Wextra,
        -Wpedantic,
        -Wconversion,
        -Wshadow,
        -Wnull-dereference,
        -Weverything,
        -Wno-declaration-after-statement,   #"Mixing declarations and code is incompatible with standards before c99."
        -Wno-cast-align,                    # Misalignment occurs when casting from u16* to u32* or similar.
        -Wno-documentation,
        -Wno-documentation-unknown-command,
        -Wno-unsafe-buffer-usage,
        -Wno-covered-switch-default,
        -Wno-switch,
        -fparse-all-comments,
        -ferror-limit=0,
    ]

If:
    PathMatch: [.*\.h, .*\.hh, .*\.hpp ]
CompileFlags:
    Add: [
        -Wno-empty-translation-unit,
        -Wno-unused-macros,
        -Wno-unused-functions,
        -Wno-reserved-id-macro,
    ]

Index:
    Background: Skip
    StandardLibrary: No
